spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tododb
    username: root
    password: K0l1m2n3
security:
  oauth2:
    client:
      clientId: 135744503441663
      clientSecret: b330da2d9625d4314d0ec09f64cab35b
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me